[RHPAM-3638] - App Fomer maven integration was not honoring the nonPr…
kiegroup/kie-soup pull request #214
Opened 2021-07-14 14:23 UTC by spolti

[RHPAM-3638] - App Fomer maven integration was not honoring the nonProxyHosts property

Signed-off-by: spolti <fspolti@redhat.com>

2021-07-15 16:27 UTC, ederign commented
@mareknovotny @spolti wants to include this on 7.52.x. Are this branch still open?

2021-07-15 16:46 UTC, jesuino requested changes
Thanks for your great work on this, @spolti  - Here are a few suggestions for improvements

2021-07-15 16:46 UTC, jesuino commented on kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java
> +            } else if (!repositoryUrlMatchNonProxyHosts(settings.getActiveProxy().getNonProxyHosts(), remoteBuilder.build().getUrl())) {
instead `settings.getActiveProxy()` use the `activeProxy` local variable.

2021-07-15 16:46 UTC, jesuino commented on kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java
> +                remoteBuilder.setProxy( getActiveAetherProxyFromSettings(settings));
```suggestion
                remoteBuilder.setProxy(getActiveAetherProxyFromSettings(settings));
```
Removing extra space

2021-07-15 16:46 UTC, jesuino commented on kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java
> +            } else if (!repositoryUrlMatchNonProxyHosts(settings.getActiveProxy().getNonProxyHosts(), remoteBuilder.build().getUrl())) {
```suggestion
            } else if (!repositoryUrlMatchNonProxyHosts(activeProxy.getNonProxyHosts(), remoteBuilder.build().getUrl())) {
```

2021-07-15 16:46 UTC, jesuino commented on kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java
> +                remoteBuilder.setProxy( getActiveAetherProxyFromSettings( settings ) );
```suggestion
                remoteBuilder.setProxy(getActiveAetherProxyFromSettings(settings));
```

Removing extra space

2021-07-15 16:46 UTC, jesuino commented on kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepositoryConfiguration.java
> +            } else if (!repositoryUrlMatchNonProxyHosts(settings.getActiveProxy().getNonProxyHosts(), artifactRepository.getUrl())) {
```suggestion
            } else if (!repositoryUrlMatchNonProxyHosts(activeProxy.getNonProxyHosts(), artifactRepository.getUrl())) {
```

2021-07-15 16:57 UTC, jesuino approved these changes
LGTM!

2021-07-16 07:22 UTC, sutaakar approved these changes
Looks good to me, works as expected.

2021-07-16 11:44 UTC, mareknovotny commented
so jira was retargeted to next major release and we can close this

2021-07-30 20:09 UTC, closed without merging